version: 0.0
os: linux
files:
  - source: .
  destination: /home/ec2-user/cse-slackbot
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root
